### ISSUE TITLE
"Receive" IAM action unknown

### ISSUE THREAD

**Issue by stevenpitts** [terraform-aws-modules/terraform-aws-sns#46]
https://github.com/terraform-aws-modules/terraform-aws-sns/blob/a75132bffa14d53088e14bae792013be533fac11/main.tf#L66

`sns:Receive` is not a recognized IAM action, as seen [in the docs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsns.html).

I haven't experienced an error from this, but from a security perspective it's unclear what its purpose is. Why is it there?

**Comment by csuttles** [comment]
I think "sns:Recieve" is from an old version of the API: http://awsdocs.s3.amazonaws.com/SNS/latest/sns-dg.pdf

**Comment by stevenpitts** [comment]
@csuttles Good find! I'll leave this issue open to see how/if they maintainers want to address it, then :+1:

**Comment by stevenpitts** [comment]
Un-stale, getting fixed in https://github.com/terraform-aws-modules/terraform-aws-sns/pull/47

**Comment by stevenpitts** [comment]
Un-stale...?

**Comment by stevenpitts** [comment]
Fixed in #47 :tada:
