### ISSUE TITLE
Missing SNS Topic policy action: "sns:Receive"

### ISSUE THREAD

**Issue by igorjanevski** [terraform-aws-modules/terraform-aws-sns#48]
## Description

AWS recently updated their SNS Topic policy actions by including additional action: "sns:Receive". You are missing this action in your module, hence those that use the module have a reported change where Terraform wants to remove this action from the policy.

Line: https://github.com/terraform-aws-modules/terraform-aws-sns/blob/master/main.tf#L62C13-L62C13

## Expected behavior

![image](https://github.com/terraform-aws-modules/terraform-aws-sns/assets/37273051/3d257370-6e7b-445a-a65b-913ae55999a9)

## Actual behavior

![image](https://github.com/terraform-aws-modules/terraform-aws-sns/assets/37273051/1ff2060b-5790-4dfc-872d-5138f5be6fa8)

## Additional context

Please fix it ASAP.

**Comment by bryantbiggs** [comment]
this has already been resolved on #47
