### ISSUE TITLE
example is not related to the sns module

### ISSUE THREAD

**Issue by kkirpichnikov** [terraform-aws-modules/terraform-aws-sns#5]
Not sure, how the example is related to the SNS module
https://github.com/terraform-aws-modules/terraform-aws-sns/blob/master/examples/complete/main.tf
Seems that it's an example of KMS.
Please, check it out.

**Comment by cfbao** [comment]
It _is_ an example of this module.
The modules accepts an optional input `kms_master_key_id` that can be used to encrypt published messages.
The example is showing the creation of an encrypted SNS topic and an unencrypted SNS topic.

**Comment by bryantbiggs** [comment]
correct - its an example that shows encrypted topic usage
