### ISSUE TITLE
Error: invalid value for statement.0.sid (must only include alphanumeric characters)

### ISSUE THREAD

**Issue by HectorQuiroz** [terraform-aws-modules/terraform-aws-sns#59]
## Description

We get the following error using this module:

```
│ Error: invalid value for statement.0.sid (must only include alphanumeric characters)
│ 
│   with module.terraform-aws-sns.data.aws_iam_policy_document.this[0],
│   on .terraform/modules/terraform-aws-sns/main.tf line 51, in data "aws_iam_policy_document" "this":
│   51: data "aws_iam_policy_document" "this" {
```

## Versions

- Module version 

- Terraform version:
v1.5.7
- Provider version(s):
4.3.0

## Reproduction Code 

This error was reproduced on our environment during a tf plan to out modules today. I test with my forked repo and this error disappeared. Creating this [PR](https://github.com/terraform-aws-modules/terraform-aws-sns/pull/60) to fix this issue.

## Actual behavior

Error deploying data,aws_iam_policy_document.this

### Terminal Output Screenshot(s)

```
│ Error: invalid value for statement.0.sid (must only include alphanumeric characters)
│ 
│   with module.terraform-aws-sns.data.aws_iam_policy_document.this[0],
│   on .terraform/modules/terraform-aws-sns/main.tf line 51, in data "aws_iam_policy_document" "this":
│   51: data "aws_iam_policy_document" "this" {
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.1.2 :tada:
