### ISSUE TITLE
count = "true" for teraform011 branch

### ISSUE THREAD

**Issue by rba1-source** [terraform-aws-modules/terraform-aws-sns#8]
For the master branch you'e changed the "count" line to evaluate to a number, but for the teraform11 branch, this evaluates by default to a string value of "true".

**Comment by bryantbiggs** [comment]
hello @rba1-source  I would recommend upgrading to terraform 0.12 to start taking advantage of these features and any additions made to master

**Comment by bryantbiggs** [comment]
closing as terraform 0.11 is no longer supported
